import { DEMO_USER_ID } from '@lib/app';
import type { ShoppingListItem } from './shoppingList.types';

export const mockShoppingList: ShoppingListItem[] = [
  {
    id: 'sl-001',
    userId: DEMO_USER_ID,
    name: 'Chicken Breast',
    ingredientId: 'ing-001',
    productId: 'prod-001',
    amount: 2,
    unit: 'lb',
    category: 'meat',
    note: 'Get the organic kind if possible',
    checked: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 24,
  },
  {
    id: 'sl-002',
    userId: DEMO_USER_ID,
    name: 'Broccoli',
    ingredientId: 'ing-002',
    productId: null,
    amount: 3,
    unit: 'piece',
    category: 'produce',
    note: null,
    checked: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 22,
  },
  {
    id: 'sl-003',
    userId: DEMO_USER_ID,
    name: 'Whole Milk',
    ingredientId: 'ing-003',
    productId: null,
    amount: 1,
    unit: 'l',
    category: 'dairy',
    note: '2% or whole - either works',
    checked: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 20,
  },
  {
    id: 'sl-004',
    userId: DEMO_USER_ID,
    name: 'Brown Rice',
    ingredientId: 'ing-004',
    productId: null,
    amount: 2,
    unit: 'cup',
    category: 'grains',
    note: null,
    checked: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 18,
  },
  {
    id: 'sl-005',
    userId: DEMO_USER_ID,
    name: 'Black Beans',
    ingredientId: 'ing-005',
    productId: null,
    amount: 1,
    unit: 'cup',
    category: 'legumes',
    note: 'Canned is fine',
    checked: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 16,
  },
  {
    id: 'sl-006',
    userId: DEMO_USER_ID,
    name: 'Olive Oil',
    ingredientId: 'ing-006',
    productId: null,
    amount: 1,
    unit: 'cup',
    category: 'oils',
    note: null,
    checked: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 14,
  },
  {
    id: 'sl-007',
    userId: DEMO_USER_ID,
    name: 'Almonds',
    ingredientId: 'ing-008',
    productId: null,
    amount: 200,
    unit: 'g',
    category: 'nuts',
    note: 'Unsalted please',
    checked: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 12,
  },
  {
    id: 'sl-008',
    userId: DEMO_USER_ID,
    name: 'Salmon Fillet',
    ingredientId: 'ing-009',
    productId: null,
    amount: 1,
    unit: 'lb',
    category: 'seafood',
    note: null,
    checked: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 10,
  },
  {
    id: 'sl-009',
    userId: DEMO_USER_ID,
    name: 'Dish soap',
    ingredientId: null,
    productId: null,
    amount: null,
    unit: null,
    category: 'other',
    note: null,
    checked: false,
    createdAt: Date.now() - 1000 * 60 * 60 * 2,
  },
];
