import { Ingredient } from './ingredients.types';

export const mockIngredients: Ingredient[] = [
  {
    id: 'ing-001',
    userId: 'demo',
    name: 'Chicken Breast',
    type: 'meat',
    imageUrl:
      'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=800&q=80',
    nutrients: {
      protein: 31,
      carbs: 0,
      fat: 3.6,
      fiber: 0,
      sugar: 0,
      sodium: 74,
      calories: 165,
    },
    currentAmount: 0,
    servingSize: 0.5,
    unit: 'lb',
    products: [
      {
        id: 'prod-001',
        retailer: 'Whole Foods',
        label: 'Organic Chicken Breast',
        cost: 11.98,
        servings: 4,
        url: null,
      },
    ],
    otherUnit: null,
    defaultProductId: 'prod-001',
    barcode: null,
  },
  {
    id: 'ing-002',
    userId: 'demo',
    name: 'Broccoli',
    type: 'produce',
    imageUrl:
      'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=800&q=80',
    nutrients: {
      protein: 2.8,
      carbs: 6.6,
      fat: 0.4,
      fiber: 2.6,
      sugar: 1.7,
      sodium: 33,
      calories: 34,
    },
    currentAmount: 3,
    servingSize: 1,
    unit: 'piece',
    products: [
      {
        id: 'prod-002',
        retailer: 'Local Farmers Market',
        label: 'Fresh Broccoli',
        cost: 3.87,
        servings: 3,
        url: null,
      },
    ],
    otherUnit: null,
    defaultProductId: 'prod-002',
    barcode: null,
  },
  {
    id: 'ing-003',
    userId: 'demo',
    name: 'Whole Milk',
    type: 'dairy',
    imageUrl:
      'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800&q=80',
    nutrients: {
      protein: 3.2,
      carbs: 4.8,
      fat: 3.3,
      fiber: 0,
      sugar: 5.1,
      sodium: 43,
      calories: 61,
    },
    currentAmount: 16,
    servingSize: 1,
    unit: 'cup',
    products: [
      {
        id: 'prod-003',
        retailer: 'Safeway',
        label: 'Organic Valley Whole Milk (Half Gallon)',
        cost: 4.99,
        servings: 8,
        url: null,
      },
    ],
    otherUnit: null,
    defaultProductId: 'prod-003',
    barcode: null,
  },
  {
    id: 'ing-004',
    userId: 'demo',
    name: 'Brown Rice',
    type: 'grains',
    imageUrl:
      'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&q=80',
    nutrients: {
      protein: 7.9,
      carbs: 77.2,
      fat: 2.9,
      fiber: 3.5,
      sugar: 0.9,
      sodium: 7,
      calories: 370,
    },
    currentAmount: 2,
    servingSize: 1,
    unit: 'lb',
    products: [
      {
        id: 'prod-004',
        retailer: 'Amazon',
        label: 'Lundberg Organic Brown Rice (2lb bag)',
        cost: 6.98,
        servings: 32,
        url: 'https://amazon.com/example',
      },
    ],
    otherUnit: null,
    defaultProductId: 'prod-004',
    barcode: null,
  },
  {
    id: 'ing-005',
    userId: 'demo',
    name: 'Black Beans',
    type: 'legumes',
    imageUrl:
      'https://images.unsplash.com/photo-1589621316382-008455b857cd?w=800&q=80',
    nutrients: {
      protein: 21.6,
      carbs: 62.4,
      fat: 0.9,
      fiber: 15.5,
      sugar: 0.3,
      sodium: 5,
      calories: 341,
    },
    currentAmount: 400,
    servingSize: 40,
    unit: 'g',
    products: [
      {
        id: 'prod-005',
        retailer: 'Trader Joes',
        label: 'Organic Black Beans Can',
        cost: 1.19,
        servings: 3,
        url: null,
      },
    ],
    otherUnit: null,
    defaultProductId: 'prod-005',
    barcode: null,
  },
  {
    id: 'ing-006',
    userId: 'demo',
    name: 'Olive Oil',
    type: 'oils',
    imageUrl:
      'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80',
    nutrients: {
      protein: 0,
      carbs: 0,
      fat: 100,
      fiber: 0,
      sugar: 0,
      sodium: 2,
      calories: 884,
    },
    currentAmount: 0,
    servingSize: 0.5,
    unit: 'oz',
    products: [
      {
        id: 'prod-006',
        retailer: 'Costco',
        label: 'Kirkland Extra Virgin Olive Oil (3L)',
        cost: 25.98,
        servings: 202,
        url: null,
      },
    ],
    otherUnit: null,
    defaultProductId: 'prod-006',
    barcode: null,
  },
  {
    id: 'ing-007',
    userId: 'demo',
    name: 'Garlic Powder',
    type: 'spices',
    imageUrl:
      'https://images.unsplash.com/photo-1580323413827-bb94e2d3e2ad?w=800&q=80',
    nutrients: {
      protein: 16.5,
      carbs: 72.7,
      fat: 0.7,
      fiber: 9,
      sugar: 2.4,
      sodium: 26,
      calories: 331,
    },
    currentAmount: 4,
    servingSize: 0.25,
    unit: 'oz',
    products: [
      {
        id: 'prod-007',
        retailer: 'Target',
        label: 'McCormick Garlic Powder',
        cost: 3.99,
        servings: 80,
        url: null,
      },
    ],
    otherUnit: null,
    defaultProductId: 'prod-007',
    barcode: null,
  },
  {
    id: 'ing-008',
    userId: 'demo',
    name: 'Almonds',
    type: 'nuts',
    imageUrl:
      'https://images.unsplash.com/photo-1508747703725-719777637510?w=800&q=80',
    nutrients: {
      protein: 21.2,
      carbs: 21.6,
      fat: 49.9,
      fiber: 12.5,
      sugar: 4.4,
      sodium: 1,
      calories: 579,
    },
    currentAmount: 1,
    servingSize: 1,
    unit: 'lb',
    products: [
      {
        id: 'prod-008',
        retailer: 'Costco',
        label: 'Blue Diamond Almonds (3lb bag)',
        cost: 26.97,
        servings: 48,
        url: null,
      },
    ],
    otherUnit: null,
    defaultProductId: 'prod-008',
    barcode: null,
  },
  {
    id: 'ing-009',
    userId: 'demo',
    name: 'Salmon Fillet',
    type: 'seafood',
    imageUrl:
      'https://images.unsplash.com/photo-1580991071449-83794d6b609e?w=800&q=80',
    nutrients: {
      protein: 20,
      carbs: 0,
      fat: 13,
      fiber: 0,
      sugar: 0,
      sodium: 59,
      calories: 208,
    },
    currentAmount: 1.5,
    servingSize: 0.5,
    unit: 'lb',
    products: [
      {
        id: 'prod-009',
        retailer: 'Whole Foods',
        label: 'Wild Caught Atlantic Salmon',
        cost: 29.98,
        servings: 4,
        url: null,
      },
    ],
    otherUnit: null,
    defaultProductId: 'prod-009',
    barcode: null,
  },
  {
    id: 'ing-010',
    userId: 'demo',
    name: 'Tomatoes',
    type: 'produce',
    imageUrl:
      'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=800&q=80',
    nutrients: {
      protein: 0.9,
      carbs: 3.9,
      fat: 0.2,
      fiber: 1.2,
      sugar: 2.6,
      sodium: 5,
      calories: 18,
    },
    currentAmount: 0,
    servingSize: 1,
    unit: 'piece',
    products: [
      {
        id: 'prod-010',
        retailer: 'Local Farmers Market',
        label: 'Organic Roma Tomatoes (4 pack)',
        cost: 3.16,
        servings: 4,
        url: null,
      },
    ],
    otherUnit: null,
    defaultProductId: 'prod-010',
    barcode: null,
  },
  {
    id: 'ing-011',
    userId: 'demo',
    name: 'Ground Beef',
    type: 'meat',
    imageUrl:
      'https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=800&q=80',
    nutrients: {
      protein: 26,
      carbs: 0,
      fat: 15,
      fiber: 0,
      sugar: 0,
      sodium: 75,
      calories: 250,
    },
    currentAmount: 3,
    servingSize: 0.5,
    unit: 'lb',
    products: [
      {
        id: 'prod-011',
        retailer: 'Safeway',
        label: '80/20 Ground Beef (1lb)',
        cost: 6.49,
        servings: 4,
        url: null,
      },
    ],
    otherUnit: null,
    defaultProductId: 'prod-011',
    barcode: null,
  },
  {
    id: 'ing-012',
    userId: 'demo',
    name: 'Cheddar Cheese',
    type: 'dairy',
    imageUrl:
      'https://images.unsplash.com/photo-1618164436241-4473940d1f5c?w=800&q=80',
    nutrients: {
      protein: 24.9,
      carbs: 1.3,
      fat: 33.1,
      fiber: 0,
      sugar: 0.5,
      sodium: 621,
      calories: 403,
    },
    currentAmount: 16,
    servingSize: 1,
    unit: 'oz',
    products: [
      {
        id: 'prod-012',
        retailer: 'Trader Joes',
        label: 'Sharp Cheddar Cheese Block (8oz)',
        cost: 5.99,
        servings: 8,
        url: null,
      },
    ],
    otherUnit: null,
    defaultProductId: 'prod-012',
    barcode: null,
  },
];
